### PR TITLE
TASK: Adjust script parts to 2.x and finish deletion

### PR DESCRIPTION
**Pull request by kitsunet**

### CODE REVIEW

**Comment by kitsunet** [comment]
@dfeyer with this a project of mine runs fine on ES 2.3, please have a look and try it yourself. Ideally merge then so your PR is the main compat PR.

**Comment by dimaip** [comment]
Tested with ES 2.3.5 and 120000 nodes, everything seems cool!

**Comment by dimaip** [comment]
@dfeyer @kitsunet shall we merge it? ES2.3 works great, I think the release would be highly appreciated.

**Comment by kitsunet** [comment]
I would be happy about it...

**Comment by dfeyer** [comment]
I merge this one, and test the PR on top of master

**Pull request merged**
